#!/bin/bash
# Next command is with sudo to avoid
sudo echo "Welcome to the Xyce environment"
echo " You are entering the interactive shell."
echo "To invoke Xyce simply run:"
echo "Xyce netlist.cir"
echo "The command xdm_bdl can be used to convert netlists of different types"
echo " into xyce netlists."
cd /home/xyce
mkdir shared
cd shared
bash
